DEFAULT_DOMAIN = '192.168.0.10'
TIMEOUT = 3
WAIT_TIMEOUT = 0.2

# User status
AVAILABLE = 'AVAILABLE'
UNAVAILABLE = 'UNAVAILABLE'
AFK = 'AFK'
IN_A_MEETING = 'In a Meeting'
STATUS_OPTIONS = [AVAILABLE, UNAVAILABLE, AFK, IN_A_MEETING]

# Messages
CHAT_MESSAGE_TYPE = 'chat'
WHITELIST_STATUS = 'whitelisted'
MUC_DEFAULT_SENDER = 'conference'

# Chat States
CHAT_STATE_KEY = 'chat_state'
CHAT_STATE_ACTIVE = 'active'
CHAT_STATE_PAUSED = 'paused'

# Rooms
AFFILIATION_TYPE = 'member'
ROOM_MESSAGE_TYPE = 'groupchat'