DEFAULT_DOMAIN = 'alumchat.xyz'
TIMEOUT = 3
WAIT_TIMEOUT = 0.2

# User status
AVAILABLE = 'AVAILABLE'
UNAVAILABLE = 'UNAVAILABLE'
AFK = 'AFK'
IN_A_MEETING = 'In a Meeting'
STATUS_OPTIONS = [AVAILABLE, UNAVAILABLE, AFK, IN_A_MEETING]

# Messages
CHAT_MESSAGE_TYPE = 'chat'
WHITELIST_STATUS = 'whitelisted'
MUC_DEFAULT_SENDER = 'conference'

# Rooms
AFFILIATION_TYPE = 'member'
ROOM_MESSAGE_TYPE = 'groupchat'